#include "librecomp/overlays.hpp"
#include "ovl_patches.hpp"

// Generated by N64Recomp - contains the section table and overlay mappings
#include "recomp_overlays.inl"

void snap::register_overlays() {
    recomp::overlays::register_overlays(
        section_table,
        num_code_sections,
        total_num_sections,
        overlay_sections_by_index
    );
}
