/**
 * Pokemon Snap: Recompiled - Overlay Registration
 *
 * Registers all overlay sections with the recomp runtime.
 * Pokemon Snap uses 48 overlay groups with exclusive_ram_id.
 */

#include "librecomp/recomp.h"
#include "ovl_patches.hpp"

// Include the auto-generated overlay table
// This file is generated by N64Recomp when processing patches.toml
#if __has_include("recomp_overlays.inl")
#include "recomp_overlays.inl"
#endif

void register_overlays() {
    // TODO: Register overlay section table with the recomp runtime
    // Each overlay group needs its ROM offset, VRAM address, and size registered
    // so the runtime can load the correct recompiled functions when the game
    // DMA's an overlay into memory.
}
