#include "librecomp/overlays.hpp"
#include "ovl_patches.hpp"

// Generated by N64Recomp from patches.toml
#if __has_include("patches_bin.h")
#include "patches_bin.h"
#include "recomp_overlays.inl"

void snap::register_patches() {
    recomp::overlays::register_patches(
        patches_bin,
        sizeof(patches_bin),
        section_table,
        num_code_sections,
        total_num_sections,
        overlay_sections_by_index
    );
}
#else
// No patches built yet
void snap::register_patches() {}
#endif
