#include "librecomp/overlays.hpp"
#include "ovl_patches.hpp"

// Generated by N64Recomp - contains section_table, num_sections, overlay_sections_by_index
#include "recomp_overlays.inl"

void snap::register_overlays() {
    recomp::overlays::overlay_section_table_data_t sections{
        .code_sections = section_table,
        .num_code_sections = num_sections,
        .total_num_sections = num_sections,
    };

    recomp::overlays::overlays_by_index_t overlays{
        .table = overlay_sections_by_index,
        .len = sizeof(overlay_sections_by_index) / sizeof(overlay_sections_by_index[0]),
    };

    recomp::overlays::register_overlays(sections, overlays);
}
